### PR TITLE
Fixes for the Windows platform

### PR DESCRIPTION
**Pull request by divdavem**
This pull request fixes sauce-connect-launcher on Windows.

Especially, without this pull request, the first execution works fine (the .zip file is downloaded, extracted and sauce-connect starts), but later executions wait forever for the binary file to appear, but as the `.exe` extension is missing, this never happens. This pull request fixes this issue.

### CODE REVIEW

**Comment by sebv** [comment]
Really not sure what happens with windows, but can we change it so that `getScBin` becomes `getPotentialScBins` and returns ['/bin/sc'] for unix/mac and  ['/bin/sc', '/bin/sc.exe'] for windows, then looks at all the potential candidates, that'll be more solid.

**Comment by divdavem** [comment]
I don't think it is needed to have an array, because there is no `/bin/sc` file on Windows, only `/bin/sc.exe`. It works the first time because there is no check that the file exists after the extraction, and because the `.exe` extension is probably automatically appended by the spawn function (or the Windows API function called by spawn).

**Comment by divdavem** [comment]
I have added another fix for Windows.
Here is the issue: using the kill function does not allow Sauce Connect to properly shutdown the tunnel on Windows, as specified in the [node.js documentation](https://nodejs.org/api/process.html#process_signal_events):

> Note that Windows does not support sending Signals, but Node.js offers some emulation with process.kill(), and child_process.kill(). Sending signal 0 can be used to test for the existence of a process. **Sending SIGINT, SIGTERM, and SIGKILL cause the unconditional termination of the target process.**

Instead of using the `kill` method, we can read the tunnel id from the output of Sauce Connect and call the REST API of Sauce Labs to properly shutdown the tunnel.
It is important to properly shut down the tunnel especially in case new tunnel identifiers are used each time a tunnel is created, because, in that case, old tunnels will never be deleted and the number of concurrent tunnel is limited.

**Comment by divdavem** [comment]
I have also added some other fixes or improvements.

**Comment by toddhgardner** [comment]
I was just about to write this same functionality in my build script--I am encountering the problem where tunnels do not get properly closed on windows. Thanks for contributing this @divdavem 

@bermi What can I do to help get this merged in?

**Comment by bermi** [comment]
@toddhgardner, @divdavem it would be helpful if people running Windows could verify the changes by running:

```
npm test
```

Once the tests are passing I can review them on Mac/Linux and push a new version to npm.

**Comment by johanneswuerbach** [comment]
@bermi should you maybe add https://www.appveyor.com/ to make sure everything works also for new changes?

**Comment by toddhgardner** [comment]
Hey @bermi, I pulled down @divdavem's changes and ran it in windows, all passing.

image

I've also been using this on my own fork for a few days now, seems to work great.

**Comment by johanneswuerbach** [comment]
Would you mind rebasing your fork one more time so we have appveyor running against it?

**Pull request closed without merging**
