### PR TITLE
Don't include your .envrc in the release

### PR DESCRIPTION
**Pull request by halkeye**
https://github.com/timoxley/pkgfiles is a good tool to see whats going to be included

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Thanks 🙏

**Comment by halkeye** [comment]
@johanneswuerbach you may want to invalidate your key too

**Comment by johanneswuerbach** [comment]
Yes, but the keys are public at the moment anyhow due to limitations in public PRs and secret credentials https://github.com/bermi/sauce-connect-launcher/blob/master/.travis.yml#L11

**Comment by halkeye** [comment]
giphub

MUAHAHA you fell for my trap.

I mean, eww public keys :(

You can use travis's encrypted env support to hide the key. You can also use recently added JWT addon (https://docs.travis-ci.com/user/jwt) to have a time limited version (though i'm not 100% sure it works with sauce connect). Also I think @BanzaiMan might be rolling it into the sauce addon instead.

**Comment by johanneswuerbach** [comment]
Maybe, but we also use appveyor https://github.com/bermi/sauce-connect-launcher/blob/master/appveyor.yml#L4

Encrypted env vars sadly don't work while still allowing PRs from forks, which makes sense as you could just print all vars in your PR.

Others workaround this by manually approving CI runs, but appveyor/travis don't support this yet.

Those keys are also created with the most limited scope and will be rolled once abuse is detected, but yeah not ideal but I also don't see an alternative for the moment :-(

**Comment by halkeye** [comment]
ah shoot, okay, well i'll keep it in mind and come back if a solution comes up.

**Comment by halkeye** [comment]
the jwt addon is specifically setup so you can do encrypted variables in PRs, it was the entire point of it. Short lived tokens that way.

**Pull request merged**
