### PR TITLE
Test against supported Node versions

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Those versions are currently maintained https://github.com/nodejs/LTS#nodejs-long-term-support-working-group

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
@jlipps what do you think of this approach? Having CI for PRs is kind of crucial. The credentials are a sub account of a free OSS account I created for this project (can be shared).

**Comment by jlipps** [comment]
Unfortunately we can't have credentials out in the open like this, as at some point they will be abused. See https://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests for more information.

**Comment by johanneswuerbach** [comment]
Agreed that this isn't an amazing solution, but the only possible way I found to test PRs, which is also used by various bigger projects. E.g. https://github.com/angular/angular.js/blob/master/.travis.yml#L25-L26 https://github.com/emberjs/ember.js/blob/master/.travis.yml#L32-L33

I'm aware that a different solution is being worked on https://github.com/travis-ci/travis-build/pull/356, but without results for nearly 2 years.

As CI for PRs is kind of a requirement for a healthy OSS project, I would merge with this hack until a better solution is available. The free OSS account supports only public builds, so abuse is relatively easy to detect (and also possible with all those other public credentials).

**Comment by jlipps** [comment]
I really don't like this but given how widespread it is I guess chances are someone would abuse a different account :-) Let's keep our eye on the Travis PR and make sure to regenerate the access key when we can take advantage of secure PRs.

**Comment by johanneswuerbach** [comment]
👍  anything else I should do here?

**Comment by jlipps** [comment]
LGTM

**Pull request merged**
