### PR TITLE
add -x param

### PR DESCRIPTION
**Pull request by fpoppinga**
Hi, 

I missed this very important detail in my last PR. 

Sadly I also defaulted the console.info in this commit and right now I have zero time to change this. 

Maybe somebody could swiftly remove the console.info, or I'll provide a different patch once I find some time.

### CODE REVIEW

**Comment by fpoppinga** [comment]
NVM, I fixed it hackily in the github editor.

**Comment by jvdieten** [comment]
Can this be merged? This is a fix for #140. 

Now tunnel is still created on US SauceLabs environment.

Thanks in advance!

**Comment by johanneswuerbach** [comment]
Thank you, released as `1.2.6`

**Comment by vgrigoruk** [comment]
Hey, @jvdieten & @fpoppinga & @johanneswuerbach. This is a breaking change for projects that are already passing `options.x` to `connect` method. I'd suggest to make a mayor release instead.
Also, what do you think about adding optional `region=us` arg in `connect` method and use it's value to determine API endpoint url?

**Comment by johanneswuerbach** [comment]
@vgrigoruk sorry about the late response, how about making this skipping this if `options.x` is already provided?

**Comment by vgrigoruk** [comment]
this could work, @johanneswuerbach (so it is at least compatible with existing code that is passing -x option).

**Pull request merged**
