### PR TITLE
Allow to set SAUCE_API_HOST via environment

### PR DESCRIPTION
**Pull request by fpoppinga**
* this is required to use the new eu-central-1 datacenter.

### CODE REVIEW

**Comment by fpoppinga** [comment]
Thanks for the quick review! I removed the `yarn.lock`. 

Best
Finn

**Comment by fpoppinga** [comment]
@jlipps , could you please re-check? :)

**Comment by fpoppinga** [comment]
@johanneswuerbach could you please recheck? :)

**Comment by johanneswuerbach** [comment]
Sure, sorry 👍

**Comment by johanneswuerbach** [comment]
Released as `v1.2.5`

**Comment by fpoppinga** [comment]
Thanks!

**Pull request merged**
