### PR TITLE
Allow work dir to be programatically set

### PR DESCRIPTION
**Pull request by marcelofarias**

### CODE REVIEW

**Comment by jlipps** [comment]
since this isn't exported or anything how is it meant to be used?

**Comment by marcelofarias** [comment]
@jlipps Ops, my bad. Btw, I'd rather call the exported function setWorkDir instead - any thoughts?

**Comment by jlipps** [comment]
`setWorkDir` seems fine

**Comment by marcelofarias** [comment]
@jlipps updated and squashed

**Comment by jlipps** [comment]
published as 0.16.0

**Pull request merged**
